# Server settings
server:
  port: 8080
  servlet:
    context-path: /file

#log
logging:
  level:
     ROOT: info
  file: file.log

spring:
    servlet:
        multipart:
          max-request-size: 100MB
          max-file-size: 100MB
    redis:
      host: 127.0.0.1
      port: 6379
      password: ShooterCheng.Pool
      database: 15
      timeout: 3000
      jedis:
        pool:
          max-active: 600
          max-idle: 30
          max-wait: 10
    data:
      mongodb:
        host: 127.0.0.1
        port: 27017
        database: mongotest
        username: chengdu
        password: Cheng.Du

remote:
    file:
       url: http://localhost:8081/mongodbstu/single/fileupload.do

file:
   engine:
      local:
         path: /home/scd/upload
      sftp:
         host: 192.168.1.101
         port: 22
         username: test
         password: testT2018
         path: /sftpupload
      ftp:
         host: 192.168.1.101
         port: 21
         username: test
         password: testT2018
         path: /ftpupload

pool:
  file:
     corePoolSize: 28
     maximumPoolSize: 66
     keepAliveTime: 60
     timeUnit: SECONDS
     blockingQueue: 2000
temp:
  breakpath: /temp/breakmerge